### PR TITLE
Fix according to linter reports

### PR DESCRIPTION
**Pull request by razvand**
Fix current content according to linting issues reported by GitHub action (`super-linter`, `spellcheck`).

### CODE REVIEW

**Review by StefanJum — COMMENTED** [review]
Looks good @razvand, but there is a conflict with the main branch.

**Review by StefanJum — CHANGES_REQUESTED** [review]
@razvand add the urls on lines 29 and 205 in backticks (I can't add code suggestions since there are no changes to those lines). That should solve the last linter errors and it should be good to go.

**Comment by razvand** [comment]
> @razvand add the urls on lines 29 and 205 in backticks (I can't add code suggestions since there are no changes to those lines). That should solve the last linter errors and it should be good to go.

I think that would be stupid. Links should be clickable and not between backticks. The spellchecker itself should ignore them. I created the [commit here](https://github.com/open-education-hub/actions/commit/f7fd8181bc7af1ac24bcc10e8b9450e0ea3d90c7), but it seems it doesn't work.

**Comment by razvand** [comment]
> > @razvand add the urls on lines 29 and 205 in backticks (I can't add code suggestions since there are no changes to those lines). That should solve the last linter errors and it should be good to go.
> 
> I think that would be stupid. Links should be clickable and not between backticks. The spellchecker itself should ignore them. I created the [commit here](https://github.com/open-education-hub/actions/commit/f7fd8181bc7af1ac24bcc10e8b9450e0ea3d90c7), but it seems it doesn't work.

Oh, I'm stupid. This is on the super-linter side. Let's disable that bare URL feature. It's stupid, IMO.

**Review by StefanJum — APPROVED** [review]
>  Let's disable that bare URL feature. It's stupid, IMO.

Agreed, see <https://github.com/open-education-hub/actions/pull/28>
All good besides.

**Comment by ananos** [comment]
ignoring linting issues & merging.

**Pull request merged**
